### ISSUE TITLE
Weird behavior if letterbox/pillarbox settings are changed after freeze

### ISSUE THREAD

**Issue by PurpleMyst** [FlyOrBoom/mercator#13]
As per the title, if you turn on freeze with some amount of pillarboxing, then reset the pillarboxing value to 0, the edges of the image will show the current camera output.

I am willing to submit a PR to fix this, however I am unsure of what the behavior should be. Should we take a new image if settings change? Should we just clear everything before drawing the frozen image?

**Comment by xingyzt** [comment]
I think the effects (pillarboxing etc) should be applied to the frozen image. This just means moving the drawing of the frozen image above the rest of the effects pipeline.

**Comment by xingyzt** [comment]
Will be making the change right now, no need for a PR submission.

**Comment by xingyzt** [comment]
Note that now there's a flash of a blank frame when freeze is checked. Not sure if it's a feature or a bug :)
