### ISSUE TITLE
"Realistic" freeze frame

### ISSUE THREAD

**Issue by PurpleMyst** [FlyOrBoom/mercator#17]
Here's a feature request/idea: Instead of having a single frame of freeze, maybe allow recording of a small fragment of video that can then be played back repeatedly to simulate motion? Maybe even played first forwards then backwards to make sure we have a perfect loop.

**Comment by xingyzt** [comment]
I know this feature would be useful for a lot of people, but the added UI and video handling will make the extension too complicated for me to maintain as a side project.

**Comment by PurpleMyst** [comment]
I've added this to my fork which can be found at https://github.com/PurpleMyst/zeno
You can check out the code in `playback.ts`, it's really not that much more than a basic freeze, most of my changes were project restructuring
