### ISSUE TITLE
WISH: Position of text

### ISSUE THREAD

**Issue by HenrikBengtsson** [FlyOrBoom/mercator#4]
It would neat if one could x-y adjust the position of the text, for instance, so that I can put my name tag at the bottom of my video stream.

PS. Thanks for this work

**Comment by xingyzt** [comment]
![image](https://user-images.githubusercontent.com/31298876/89720658-6ff07d00-d989-11ea-9517-9ac827465c43.png)
Wish granted! The text input is now a <textarea>, so you can do a bunch of linebreaks before or after the text to position it up or down.

**Comment by HenrikBengtsson** [comment]
Thxs.
