### ISSUE TITLE
[Feature Request] Add a way to completely hide the bar

### ISSUE THREAD

**Issue by richardwei6** [FlyOrBoom/mercator#8]
The bar that creates a dropdown menu is too big and can obstruct the top left camera.

A suggestion could be to have a small sliver of the menu which can pull down when the mouse hovers over it.

**Comment by xingyzt** [comment]
Wish granted! Coming in update 1.15.0
![image](https://user-images.githubusercontent.com/31298876/101863610-786be680-3b28-11eb-8de6-5edff17072f2.png)
![image](https://user-images.githubusercontent.com/31298876/101863575-72760580-3b28-11eb-97cd-ed4b20521a0b.png)
