### ISSUE TITLE
[Feature Request] Background blur

### ISSUE THREAD

**Issue by mcollica** [FlyOrBoom/mercator#9]
As per title

**Comment by xingyzt** [comment]
Google Meet has already implemented background blur natively. Image segmentation libraries are also too much to fit into my single-script implementation.

**Comment by mcollica** [comment]
There is no native blur on Firefox. Got it anyway, thanks anyway.

**Comment by mcollica** [comment]
> Google Meet has already implemented background blur natively.

There is no native background blur with Google Meet on Firefox.

> Image segmentation libraries are also too much to fit into my single-script implementation.

Got it, thanks anyway.
